#! /bin/bash

a2ps ./ui/controllers/*.h \
./ui/controllers/*.cpp \
./ui/views/*.h \
./ui/views/*.cpp \
./ui/views/design/*.h \
./ui/views/design/*.cpp \
./ui/views/runtime/*.h \
./ui/views/runtime/*.cpp \
./server/*.h \
./server/*.cpp \
./server/game/*.h \
./server/game/*.cpp \
./server/game/client/*.h \
./server/game/client/*.cpp \
./server/game/commands/*.h \
./server/game/commands/*.cpp \
./server/game/commands/exceptions/*.h \
./server/game/commands/exceptions/*.cpp \
./server/game/levels/*.h \
./server/game/levels/*.cpp \
./server/game/levels/exceptions/*.h \
./server/game/levels/exceptions/*.cpp \
./server/game/messages/*.h \
./server/game/messages/*.cpp \
./server/game/sessions/*.h \
./server/game/sessions/*.cpp \
./game/core/*.h \
./game/core/*.cpp \
./game/core/affectors/*.h \
./game/core/affectors/*.cpp \
./game/design/*.h \
./game/design/*.cpp \
./game/design/connect/*.h \
./game/design/connect/*.cpp \
./game/design/elements/*.h \
./game/design/elements/*.cpp \
./game/design/move/*.h \
./game/design/move/*.cpp \
./game/logic/*.h \
./game/logic/*.cpp \
./game/logic/properties/*.h \
./game/logic/properties/*.cpp \
./game/serialization/*.h \
./game/serialization/*.cpp \
./game/serialization/model/*.h \
./game/serialization/model/*.cpp \
./game/serialization/persistence/*.h \
./game/serialization/persistence/*.cpp \
./game/serialization/service/*.h \
./game/serialization/service/*.cpp \
./editor/*.cpp \
./editor/persistence/*.h \
./editor/persistence/*.cpp \
./common/constants/*.h \
./common/constants/*.cpp \
./common/logger/*.h \
./common/logger/*.cpp \
./common/protocol/*.h \
./common/protocol/*.cpp \
./common/sockets/*.h \
./common/sockets/*.cpp \
./common/sockets/exceptions/*.h \
./common/sockets/exceptions/*.cpp \
./common/threads/*.h \
./common/threads/*.cpp \
./common/threads/locks/*.h \
./common/threads/locks/*.cpp \
./common/utils/*.h \
./common/utils/*.cpp \
./client/*.cpp \
./client/game/*.h \
./client/game/*.cpp \
./client/game/commands/*.h \
./client/game/commands/*.cpp \
./client/game/commands/exceptions/*.h \
./client/game/commands/exceptions/*.cpp \
./client/game/facade/*.h \
./client/game/facade/*.cpp \
./client/game/model/*.h \
./client/game/model/*.cpp \
./client/game/model/exceptions/*.h \
./client/game/model/exceptions/*.cpp \
./client/ui/*.h \
./client/ui/*.cpp \
./client/ui/controllers/*.h \
./client/ui/controllers/*.cpp \
./client/ui/widgets/*.h \
./client/ui/widgets/*.cpp \
-Av --header="[75.42] Taller de programacion I - TP Final" \
--footer="2do Cuatrimestre 2008" \
--line-numbers=1 --borders=yes --columns=2  --landscape --output=code.ps \
--tabsize=2 --major=columns --toc -E
